ansible_user: "{{ lookup('env', 'USER') }}"
ansible_ssh_private_key_file: /home/{{ansible_user}}/.ssh/id_rsa_sysadmin


network:
  interface: enp0s3


debian_iso:
  version: "13.1.0"
  name: "debian-13.1.0-amd64-netinst.iso"
  download_dir: "{{ lookup('env', 'HOME') }}/Downloads"

project_paths:
  base: /vm
  iso: /vm/iso